/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f7f9ff',
        'surface-dim': '#cddbee',
        'surface-bright': '#f7f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#edf4ff',
        'surface-container': '#e3efff',
        'surface-container-high': '#dbeafd',
        'surface-container-highest': '#d5e4f7',
        'on-surface': '#0e1d2a',
        'on-surface-variant': '#44474e',
        'inverse-surface': '#243240',
        'inverse-on-surface': '#e8f1ff',
        'outline': '#74777f',
        'outline-variant': '#c4c6cf',
        'surface-tint': '#465f88',
        'primary': '#000a1e',
        'on-primary': '#ffffff',
        'primary-container': '#002147',
        'on-primary-container': '#708ab5',
        'inverse-primary': '#aec7f6',
        'secondary': '#115eae',
        'on-secondary': '#ffffff',
        'secondary-container': '#70aafe',
        'on-secondary-container': '#003d77',
        'tertiary': '#000a21',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00204c',
        'on-tertiary-container': '#3f86f8',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#aec7f6',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#2d476f',
        'secondary-fixed': '#d5e3ff',
        'secondary-fixed-dim': '#a7c8ff',
        'on-secondary-fixed': '#001c3b',
        'on-secondary-fixed-variant': '#004788',
        'tertiary-fixed': '#d8e2ff',
        'tertiary-fixed-dim': '#adc6ff',
        'on-tertiary-fixed': '#001a41',
        'on-tertiary-fixed-variant': '#004493',
        'background': '#f7f9ff',
        'on-background': '#0e1d2a',
        'surface-variant': '#d5e4f7',
        'ashoka-gold': '#B3802A',
        'portal-bg': '#F4F6F9',
        'surface-white': '#FFFFFF',
        'border-grid': '#DCE3EC',
        'border-strong': '#B0C0D4',
        'card-district': '#E8EEFA',
        'card-block': '#FDEAEB',
        'card-panchayat': '#EBF3FC',
        'card-village': '#E8F8F0',
        'tier-1-critical': '#F7D9CE',
        'tier-2-low': '#F3B39E',
        'tier-3-moderate': '#BCD9EA',
        'tier-4-progress': '#6BAED6',
        'tier-5-high': '#2171B5',
        'tier-6-saturated': '#08306B',
        'water-safe': '#1A7F48',
        'water-alert': '#C82333'
      },
      spacing: {
        'gutter': '1rem',
        'gutter-mobile': '0.75rem',
        'margin': '2rem',
        'margin-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem'
      },
      fontFamily: {
        'sans': ['"Public Sans"', 'sans-serif'],
        'label-numeric': ['"JetBrains Mono"', 'monospace'],
        'jetbrains': ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        'sm': '0.125rem',
        DEFAULT: '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      }
    },
  },
  plugins: [],
}