import os
import time
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_fscore_support
from diagnostics import evaluate_telemetry

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Test datasets generated by Dev 1 in /simulation
DATASETS = {
    "Normal Baseline Feed": os.path.join(BASE_DIR, '../simulation/telemetry_feed.csv'),
    "Clog / Blockage Feed": os.path.join(BASE_DIR, '../simulation/clog_fault_feed.csv'),
    "Pump Fault Feed": os.path.join(BASE_DIR, '../simulation/pump_fault_feed.csv')
}

def run_evaluation():
    print("==================================================")
    print("   JALSETU ML ENGINE — PERFORMANCE EVALUATION    ")
    print("==================================================\n")

    all_y_true = []
    all_y_pred = []
    latencies_ms = []

    for name, path in DATASETS.items():
        if not os.path.exists(path):
            print(f"⚠️ Skipping {name}: File not found at {path}")
            continue

        print(f"Evaluating dataset: {name} ({os.path.basename(path)})...")
        df = pd.read_csv(path)

        # Standardize column mapping
        df_mapped = pd.DataFrame()
        df_mapped['pressure'] = df.get('pressure', df.get('pressure_bar', 0))
        df_mapped['flow'] = df.get('flow', df.get('flow_rate_lps', 0))
        df_mapped['current'] = df.get('current', df.get('motor_current_amp', df.get('motor_amps', 0)))
        df_mapped['voltage'] = df.get('voltage', df.get('grid_voltage_v', 220))
        
        # Ground truth label (1 = Anomaly / Fault, 0 = Normal)
        if 'is_anomaly' in df.columns:
            y_true = df['is_anomaly'].astype(int).tolist()
        elif 'ground_truth_label' in df.columns:
            y_true = (df['ground_truth_label'] != 'NORMAL').astype(int).tolist()
        else:
            # Default fallback assumption based on dataset filename
            y_true = [0 if "telemetry_feed" in path else 1] * len(df)

        y_pred = []

        for _, row in df_mapped.iterrows():
            record = row.to_dict()
            
            # Benchmark inference latency per sample
            start_time = time.perf_counter()
            result = evaluate_telemetry(record)
            end_time = time.perf_counter()
            
            latencies_ms.append((end_time - start_time) * 1000)

            # Map diagnostic outcome (1 = Fault/Warning, 0 = Normal)
            is_fault = 0 if result['status'] == 'NORMAL' else 1
            y_pred.append(is_fault)

        all_y_true.extend(y_true)
        all_y_pred.extend(y_pred)

    if not all_y_true:
        print("❌ Error: No datasets were successfully evaluated.")
        return

    # Compute Global Evaluation Metrics
    precision, recall, f1, _ = precision_recall_fscore_support(all_y_true, all_y_pred, average='binary')
    cm = confusion_matrix(all_y_true, all_y_pred)
    avg_latency = np.mean(latencies_ms)

    print("\n--------------------------------------------------")
    print("              FINAL MODEL METRICS                ")
    print("--------------------------------------------------")
    print(f"🎯 Precision : {precision * 100:.2f}% (Low false alarm rate)")
    print(f"🎯 Recall    : {recall * 100:.2f}% (High fault detection rate)")
    print(f"🎯 F1-Score  : {f1 * 100:.2f}% (Balanced accuracy)")
    print(f"⚡ Avg Speed : {avg_latency:.3f} ms / inference (Edge-Ready)")
    print("--------------------------------------------------")
    print("\n📊 Confusion Matrix [ [TN, FP], [FN, TP] ]:")
    print(cm)
    print("==================================================\n")

if __name__ == '__main__':
    run_evaluation()